import json
import redis
import requests
import time
import hashlib
from datetime import datetime, timedelta
import os
import logging

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class NotificationService:
    def __init__(self):
        self.redis_client = redis.from_url(os.getenv("REDIS_URL", "redis://localhost:6379"))
        self.sendgrid_api_key = os.getenv("SENDGRID_API_KEY")
        self.notification_email = os.getenv("NOTIFICATION_EMAIL", "marcelbutucea@gmail.com")
        self.slack_webhook = os.getenv("SLACK_WEBHOOK")
        self.running = True
        
        logger.info(f"SendGrid key configured: {'Yes' if self.sendgrid_api_key else 'No'}")
        logger.info(f"Notification email: {self.notification_email}")
        
        # Deduplication settings
        self.dedup_window_hours = 6
        
    def generate_alert_hash(self, alert):
        """Generate hash for alert deduplication"""
        content_string = f"{alert['job_id']}:{alert['title']}:{alert['source_url']}"
        return hashlib.md5(content_string.encode()).hexdigest()
    
    def is_duplicate_alert(self, alert):
        """Check if alert is a duplicate within time window"""
        alert_hash = self.generate_alert_hash(alert)
        recent_key = f"recent_alert:{alert_hash}"
        
        if self.redis_client.exists(recent_key):
            return True
        
        # Mark as seen for next 6 hours
        self.redis_client.setex(recent_key, 6 * 3600, "1")
        return False
    
    def send_sendgrid_email(self, subject, body_text, body_html=None):
        """Send email via SendGrid"""
        try:
            if not self.sendgrid_api_key:
                logger.error("SendGrid API key not configured!")
                return False
            
            logger.info(f"Sending email to {self.notification_email}")
            
            # SendGrid API payload
            payload = {
                "personalizations": [
                    {
                        "to": [{"email": self.notification_email}]
                    }
                ],
                "from": {"email": "marcelbutucea@gmail.com"},
                "subject": subject,
                "content": [
                    {"type": "text/plain", "value": body_text}
                ]
            }
            
            # Add HTML content if provided
            if body_html:
                payload["content"].append({"type": "text/html", "value": body_html})
            
            # Send request
            response = requests.post(
                "https://api.sendgrid.com/v3/mail/send",
                headers={
                    "Authorization": f"Bearer {self.sendgrid_api_key}",
                    "Content-Type": "application/json"
                },
                json=payload,
                timeout=10
            )
            
            logger.info(f"SendGrid response: {response.status_code}")
            
            if response.status_code == 202:
                logger.info(f"✅ Email sent successfully to {self.notification_email}")
                return True
            else:
                logger.error(f"SendGrid error: {response.status_code} - {response.text}")
                return False
                
        except Exception as e:
            logger.error(f"Failed to send email: {e}")
            return False
    
    def format_alert_content(self, alert):
        """Format alert content for notifications"""
        text_content = f"""
🚨 NEW AI ALERT: {alert['title']}

Relevance Score: {alert['relevance_score']}/100
Source: {alert['source_url']}
Time: {alert['timestamp']}

Summary:
{alert['content']}

---
Your AI Monitoring System found this relevant content!
        """
        
        html_content = f"""
        <html>
        <body>
            <h2>🚨 AI Pipeline Alert: {alert['title']}</h2>
            
            <p><strong>Relevance Score:</strong> {alert['relevance_score']}/100</p>
            <p><strong>Source:</strong> <a href="{alert['source_url']}">{alert['source_url']}</a></p>
            <p><strong>Time:</strong> {alert['timestamp']}</p>
            
            <h3>Summary:</h3>
            <p>{alert['content']}</p>
            
            <hr>
            <p><small>This alert was generated by your AI Monitoring System</small></p>
        </body>
        </html>
        """
        
        return text_content, html_content
    
    def process_alert(self, alert):
        """Process a single alert"""
        logger.info(f"Processing alert: {alert['title']}")
        
        # Check for duplicates
        if self.is_duplicate_alert(alert):
            logger.info(f"Skipping duplicate alert: {alert['title']}")
            return
        
        # Format content
        text_content, html_content = self.format_alert_content(alert)
        
        # Send email notification
        email_subject = f"🚨 AI Alert: {alert['title']}"
        email_sent = self.send_sendgrid_email(email_subject, text_content, html_content)
        
        # Mark alert as processed (store as strings only)
        processed_alert = {
            'job_id': str(alert['job_id']),
            'title': str(alert['title']),
            'processed_at': datetime.now().isoformat(),
            'email_sent': 'true' if email_sent else 'false',
            'relevance_score': str(alert['relevance_score'])
        }
        
        try:
            self.redis_client.hset(f"processed_alert:{alert['job_run_id']}", mapping=processed_alert)
        except Exception as e:
            logger.warning(f"Could not store processed alert: {e}")
        
        logger.info(f"Alert processed - Email sent: {email_sent}")
    
    def run_processor(self):
        """Main alert processing loop"""
        logger.info("Notification Service started with SendGrid")
        
        while self.running:
            try:
                # Get alert from queue (blocking with 1 second timeout)
                alert_data = self.redis_client.brpop("alert_queue", timeout=1)
                
                if alert_data:
                    # Parse alert
                    alert = json.loads(alert_data[1])
                    
                    # Process alert
                    self.process_alert(alert)
                
            except Exception as e:
                logger.error(f"Error processing alert: {e}")
                time.sleep(1)
    
    def stop(self):
        """Stop the notification service"""
        self.running = False

if __name__ == "__main__":
    service = NotificationService()
    
    try:
        service.run_processor()
    except KeyboardInterrupt:
        logger.info("Shutting down notification service...")
        service.stop()
